export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';
export const UPDATE_REFRESH_TOKEN = 'UPDATE_REFRESH_TOKEN';
export const UPDATE_JWT_PAYLOAD = 'UPDATE_JWT_PAYLOAD';
export const VERIFY_AUTH = 'VERIFY_AUTH';
export const DESTROY_AUTH = 'DESTROY_AUTH';
